name: Create Draft Release
on:
  push:
    tags:
      - '*'

jobs:
  create-draft-release:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all git refs
        run: |
          git fetch --tags --all

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-cleanup: always

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Generate changelog
        run: ./gradlew generateChangelog --stacktrace

      - name: Create draft release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
          body_path: build/changelog.md
